/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/history`; params?: Router.UnknownInputParams; } | { pathname: `/app/home`; params?: Router.UnknownInputParams; } | { pathname: `/app/settings`; params?: Router.UnknownInputParams; } | { pathname: `/app/components/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/app/history`; params?: Router.UnknownOutputParams; } | { pathname: `/app/home`; params?: Router.UnknownOutputParams; } | { pathname: `/app/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/app/components/CustomDrawerContent`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/app/history${`?${string}` | `#${string}` | ''}` | `/app/home${`?${string}` | `#${string}` | ''}` | `/app/settings${`?${string}` | `#${string}` | ''}` | `/app/components/CustomDrawerContent${`?${string}` | `#${string}` | ''}` | `/styles/colors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/history`; params?: Router.UnknownInputParams; } | { pathname: `/app/home`; params?: Router.UnknownInputParams; } | { pathname: `/app/settings`; params?: Router.UnknownInputParams; } | { pathname: `/app/components/CustomDrawerContent`; params?: Router.UnknownInputParams; } | { pathname: `/styles/colors`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
